### ISSUE TITLE
Need to associate role?

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/occm#187]
Page: [Launching Cloud Manager from the AWS Marketplace](https://docs.netapp.com/us-en/occm/task_launching_aws_mktp.html)

Shouldn't we have a step that says that you need to associate the role that you create in Step 1 to the Cloud Manager instance when you are deploying it through the marketplace. (Launch with EC2 console).  At this step that I have attached in an image.

![OCCM-Role](https://user-images.githubusercontent.com/519212/63226244-a5fb8680-c1a5-11e9-91f8-0d5cac31e598.png)

**Comment by netapp-bcammett** [comment]
Thanks for the feedback, Richard.

Step 4b says to select the IAM role:

Select a VPC, subnet, IAM role, and other configuration options that meet your requirements.

But we can make this more apparent by clarifying that it's the role that you created in step 1 and also by adding a screenshot. 

I also need to update other steps because the AWS Marketplace has changed a bit.

**Comment by netapp-bcammett** [comment]
These changes were implemented on 3 Sept. Thanks again for your feedback.

https://docs.netapp.com/us-en/occm/task_launching_aws_mktp.html

**Comment by nichollri** [comment]
Looks great!
