### ISSUE TITLE
Incorrect boot disk size

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetAppDocs/occm#192]
Page: [Default configurations](https://docs.netapp.com/us-en/occm/reference_default_configs.html)
Regarding the boot disk size:
_One Provisioned IOPS SSD disk for boot data, which is approximately 45 GB and 1,250 PIOPS_

The boot disk size shows 45 GB but the current ONTAP 9.6 uses a 86 GiB boot disk, not 45 GB.

**Comment by netapp-bcammett** [comment]
Pablo,

Thank you for submitting this issue. I have corrected it in the docs and I will file a bug against Cloud Manager because this same information appears in the product. I should also point out that the boot data resides on a GP2 disk, not PIOPS.

https://docs.netapp.com/us-en/occm/reference_default_configs.html#aws

Thanks again.
