### ISSUE TITLE
Question about stackdriver API mentioned on this page

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/occm#266]
Page: [Getting started with Cloud Volumes ONTAP in Google Cloud Platform](https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html)

Hi Ben, I couldn't find the "Stackdriver Logging API" listed in step 4 of this page in GCP when searching for APIs.  Is this still required and/or has the name changed?

Thanks,
Steve

**Comment by netapp-bcammett** [comment]
Hi Steve,

Thank you for your feedback and hope you're doing well. I googled and found this statement in Google's docs:

"The Stackdriver Logging API v1 has been deprecated. You must migrate your code to the v2 API before March 30, 2017."

Source: https://cloud.google.com/logging/docs/reference/v1beta3/rest

It looks like the v2 API is called the “Cloud Logging API”

I've contacted my sources in development to see whether this new v2 API is required. You can go ahead and enable it if you want, or you can see what happens if you don't.

Regards,
Ben

**Comment by definitelynotsteve** [comment]
Ben,

You’re awesome!  Thank you for finding that (and sorry I didn’t search hard enough!)  I’ll do some testing when I next have an opportunity.
-Steve

**Comment by netapp-bcammett** [comment]
Steve,

I confirmed that the "Cloud Logging API" is required for Cloud Volumes ONTAP. I'll update the docs.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Doc updates have been made. Thanks again!
