### ISSUE TITLE
When you change the storage class, inactive data starts in the Standard storage class and moves to the storage class that you selected, if the data is not accessed after 30 days.

### ISSUE THREAD

**Issue by sanjeshu** [NetAppDocs/occm#293]
Page: [Data tiering overview](https://docs.netapp.com/us-en/occm/concept_data_tiering.html)

Can we add a statement here stating  " What will happen if customer change from S3 IA to S3 "
How much time it will take to move the data back.

**Comment by netapp-bcammett** [comment]
Hello,

Thank you for taking the time to provide your feedback. I've reached out to the product team for confirmation. I'll update the docs after I hear back.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I just wanted to add an update. I have confirmed that nothing happens from the ONTAP side when you change the storage class for tiered data. ONTAP doesn't know anything about this. Cloud Manager initiates an S3 action that transitions the data from one storage class to another. 

When you change the storage class from Standard to another storage class, the data transitions to the other storage class after 30 days of inactivity. I don't see any information in the Amazon docs that confirms what happens if you change the storage class from Standard-Infrequent Access back to Standard, but the assumption is that the data transitions immediately.

Regards,
Ben

**Comment by netapp-tonacki** [comment]
Hi sanjeshu, Cloud Tiering just added some new functionality for newly tiered cluster data a couple days ago around the question you brought up - so I just wanted to let you know:

- Now you can choose the number of days data sits in 1 tier before moving to the next tier - instead of the hardcoded 30 days.
- In Google Cloud Storage you can move tiered data to multiple storage tiers over time.
- Now you can move data back to the performance tier (ONTAP) from the cloud tier.

See [what's new in Cloud Tiering](https://docs.netapp.com/us-en/occm/reference_new_occm.html#cloud-tiering-enhancements) for more details and links.

Thanks, Tom

**Comment by netapp-bcammett** [comment]
This functionality is controlled on Amazon's side.
