### ISSUE TITLE
Changing Marketplace subscription not available

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/occm#296]
Page: [Modifying Cloud Volumes ONTAP systems](https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html)

On this page under the "Changing your AWS Marketplace subscription" there are instructions for changing the marketplace subscription used for a CVO instance.  

Step 2 states "From the working environment in Cloud Manager, click the menu icon, and then click Marketplace Subscription." 

There is no "Marketplace Subscription" option in the menu of a working environment.

**Comment by netapp-bcammett** [comment]
Thank you for your feedback on the documentation. I've reached out to the product team to get clarification. I should hopefully have a response for you by tomorrow.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
@mimitche 

I confirmed that the "Marketplace Subscription" option is no longer available in Cloud Manager. I removed that section from the documentation.

That option was removed because AWS subscriptions are now associated with AWS credentials, not individual instances. 

The following pages provide information about how AWS credentials and subscriptions work with Cloud Manager:
https://docs.netapp.com/us-en/occm/concept_accounts_aws.html
https://docs.netapp.com/us-en/occm/task_adding_aws_accounts.html

Please let me know if anything is unclear and I'll do my best to clarify.

Regards,
Ben
