### ISSUE TITLE
Addition of ransomaware file extensions updates

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/occm#631]
Page: [Improving protection against ransomware](https://docs.netapp.com/us-en/occm/task_protecting_ransomware.html)

If we have the information, it would be beneficial to add a Tip here around how ransomware extensions are updated.
Something like: Ransomware file extensions are updated automatically in this way or that way.

Regards.

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Great question. I'll look into it and see what I can find.

Thanks,
Ben

**Comment by gabrieltokyo** [comment]
Yes.
Basically, extensions may change over time so customers may want to know if we keep updating the list of extensions.

If we have an easy writing for a tip, would be great to have it in the document.

If the explanation is too complex or we don't do specific updates of extensions, not needed.
Maybe just a short note on extension list gets updated on each ONTAP version up.

Regards,

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

The list of extensions that are blocked when you enable FPolicy from Cloud Manager, is a default list that's based on what Cloud Manager configures on Cloud Volumes ONTAP. The list of extensions doesn't change based on the version of ONTAP. 

The list of extensions hasn't changed since Cloud Manager introduced this feature. If needed, a customer can customize the list of file extensions by using the Cloud Volumes ONTAP CLI. 

I can add these details to the docs.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I updated the docs with the information mentioned in my previous comment.

https://docs.netapp.com/us-en/occm/task_protecting_ransomware.html

Please let me know if you feel that any other changes are needed.

Thanks as always!
Ben
