### ISSUE TITLE
No one can update the CVO using a local image with this procedure.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/occm#896]
Page: [Upgrading Cloud Volumes ONTAP software](https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html)

No one can update the CVO using a local image with this procedure. The following two pieces of information are missing.

In which folder of the Cloud Connector the ONTAP image should be placed
How to specify the path from the Cloud Manager SaaS UI for that local image

**Comment by netapp-bcammett** [comment]
@kanitani,

Thank you for reaching out. I looked at the "Update Cloud Volumes ONTAP option" in the user interface and I no longer see the option to update Cloud Volumes ONTAP using an image available on the system. That's what the documentation is referring to. I've reached out to the product team to seek clarification. If that option was removed, then I will remove that section from the documentation.

Thanks again for submitting this feedback.

Regards,
Ben

**Comment by kanitani** [comment]
Ben,

> I looked at the "Update Cloud Volumes ONTAP option" in the user interface

Which user interface do you refer to? I pointed out the section below.
https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-by-using-a-local-image

Upgrading by using a local image

Each Cloud Volumes ONTAP system can hold two software images: the current
image that is running, and an alternate image that you can boot. Cloud
Manager can change the alternate image to be the default image.
Steps

   1.

   From the working environment, click the menu icon, and then click Advanced
   > Update Cloud Volumes ONTAP.
   2.

   On the update software page, select the alternate image, and then
click Change
   Image.
   3.

   Click Proceed to confirm.

Result

Cloud Manager starts the software update. You can perform actions on the
working environment once the software update is complete.
After you finish

If you suspended SnapMirror transfers, use System Manager to resume the
transfers.

Regards,
Kan Itani


2022年3月24日(木) 20:50 Ben Cammett ***@***.***>:

**Comment by netapp-bcammett** [comment]
@kanitani,

I just received confirmation that this option was removed from Cloud Manager. So that explains why no one can update Cloud Volumes ONTAP using this procedure! :grinning:

The documentation was referring to the first option shown here:
![image](https://user-images.githubusercontent.com/18287750/159912201-1cf160e8-bc79-4fb4-bdd4-477999a2903b.png)

But that option is gone. We only have the second option now:
![image](https://user-images.githubusercontent.com/18287750/159912292-32a009be-0afd-4bb9-bc9d-42b6445e54a5.png)

I will update the docs shortly to reflect this change.

**Comment by kanitani** [comment]
I cannot understand what you mean.
Still we can update the ONTAP image using this UI. And we can specify the
local image which is on the cloud connector.
Download an image onto the cloud connector. Then we can  specify a local
image which is on the cloud connector in this UI.

[image: image.png]

Kan Itani

2022年3月24日(木) 21:04 Ben Cammett ***@***.***>:

**Comment by kanitani** [comment]
We can still upgrade CVO using local images placed into the path "
/opt/application/netapp/cloudmanager/docker_occm/data/ontap/images/"
(1) Login to the cloud connector and download an image.
  wget https://......./IMAGE_FILE_NAME
(2) Place the image to
/opt/application/netapp/cloudmanager/docker_occm/data/ontap/images/
    cp IMAGE_FILE_NAME
/opt/application/netapp/cloudmanager/docker_occm/data/ontap/images/
(3) Specify the image path in the UI "Select an image available from a URL"
   Example: http://<CloudConnector private IP>
/ontap/images/<IMAGE_FILE_NAME>
[image: image.png]
Kan Itani

2022年3月24日(木) 21:30 Ben Cammett ***@***.***>:

**Comment by netapp-bcammett** [comment]
Kan,

I removed the section about upgrading by using a local image since that's no longer an option from Cloud Manager (a _local_ image is an image already on the Cloud Volumes ONTAP system).

I updated the section about upgrading by using an image on an HTTP server. I included the examples that you provided.
https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-from-an-image-available-at-a-url

Thanks,
Ben
